/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Interface;

import java.util.Date;
import persistencia.IncluirEditar;
import Classes.Aluno;
import javax.swing.JOptionPane;

/**
 *
 * @author roger
 */
public class JifCadastro extends javax.swing.JInternalFrame {

    int acao;
    int ativo;
    Aluno objAluno = new Aluno();
    IncluirEditar IncEdi;
    
    /**
     * Creates new form JifCadastro
     */
    public JifCadastro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jcod = new javax.swing.JTextField();
        jnome = new javax.swing.JTextField();
        jbpesquisar = new javax.swing.JButton();
        jcpf = new javax.swing.JTextField();
        jrg = new javax.swing.JTextField();
        jtelefone = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jendereço = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jrsim = new javax.swing.JRadioButton();
        jrnao = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        jbnovo = new javax.swing.JButton();
        jbeditar = new javax.swing.JButton();
        jbsalvar = new javax.swing.JButton();
        jbsair = new javax.swing.JButton();
        jbexcluir = new javax.swing.JButton();
        jbcancelar = new javax.swing.JButton();
        jdata = new com.toedter.calendar.JDateChooser();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Cadastro de Alunos");
        getContentPane().setLayout(null);
        getContentPane().add(jcod);
        jcod.setBounds(10, 40, 70, 30);

        jnome.setEnabled(false);
        getContentPane().add(jnome);
        jnome.setBounds(90, 40, 380, 30);

        jbpesquisar.setText("...");
        getContentPane().add(jbpesquisar);
        jbpesquisar.setBounds(480, 40, 90, 30);

        jcpf.setEnabled(false);
        getContentPane().add(jcpf);
        jcpf.setBounds(10, 130, 170, 30);

        jrg.setEnabled(false);
        getContentPane().add(jrg);
        jrg.setBounds(230, 130, 200, 30);

        jtelefone.setEnabled(false);
        getContentPane().add(jtelefone);
        jtelefone.setBounds(470, 130, 180, 30);

        jendereço.setColumns(20);
        jendereço.setRows(5);
        jendereço.setEnabled(false);
        jScrollPane1.setViewportView(jendereço);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 210, 600, 100);

        jLabel1.setText("Cod.");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 20, 60, 14);

        jLabel2.setText("Nome:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(90, 20, 90, 14);

        jLabel3.setText("Data Cadastro.:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(590, 20, 70, 14);

        jLabel4.setText("CPF:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 110, 30, 14);

        jLabel5.setText("RG:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(230, 110, 30, 14);

        jLabel6.setText("Telefone:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(470, 110, 60, 14);

        jLabel7.setText("Endereço:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 190, 120, 14);

        buttonGroup1.add(jrsim);
        jrsim.setText("Sim");
        getContentPane().add(jrsim);
        jrsim.setBounds(620, 250, 60, 23);

        buttonGroup1.add(jrnao);
        jrnao.setText("Não");
        getContentPane().add(jrnao);
        jrnao.setBounds(620, 270, 45, 23);

        jLabel8.setText("Ativo:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(630, 230, 29, 14);

        jbnovo.setText("Novo");
        jbnovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbnovoActionPerformed(evt);
            }
        });
        getContentPane().add(jbnovo);
        jbnovo.setBounds(10, 320, 90, 30);

        jbeditar.setText("Editar");
        jbeditar.setEnabled(false);
        jbeditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbeditarActionPerformed(evt);
            }
        });
        getContentPane().add(jbeditar);
        jbeditar.setBounds(170, 320, 80, 30);

        jbsalvar.setText("Salvar");
        jbsalvar.setEnabled(false);
        jbsalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbsalvarActionPerformed(evt);
            }
        });
        getContentPane().add(jbsalvar);
        jbsalvar.setBounds(310, 320, 100, 30);

        jbsair.setText("Sair");
        getContentPane().add(jbsair);
        jbsair.setBounds(450, 320, 90, 30);

        jbexcluir.setText("Excluir");
        jbexcluir.setEnabled(false);
        getContentPane().add(jbexcluir);
        jbexcluir.setBounds(590, 320, 90, 30);

        jbcancelar.setText("Cancelar");
        jbcancelar.setEnabled(false);
        getContentPane().add(jbcancelar);
        jbcancelar.setBounds(10, 370, 90, 30);

        jdata.setEnabled(false);
        getContentPane().add(jdata);
        jdata.setBounds(600, 40, 160, 30);

        setBounds(0, 0, 1216, 788);
    }// </editor-fold>//GEN-END:initComponents

    private void jbnovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbnovoActionPerformed

        // Funções que ficarão ativas quando o Botão "NOVO" estiver em uso
       
        novo();
        Date dataSistema = new Date();
        jdata.setDate(dataSistema);
        acao=1;
        jrsim.setSelected(true);
    

    }//GEN-LAST:event_jbnovoActionPerformed

    private void jbsalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbsalvarActionPerformed
        
    // Desativando as funções quando o Botão "SALVAR" for acionado
        
            int cod;
            objAluno = new Aluno();
            preencher_objetos();
        
            if(jrsim.isSelected()){
            ativo=1;
            }
            if(jrnao.isSelected()) {
            ativo=0;
            }
            
            
            try {
                objAluno.setA_dtcadastro (jdata.getDate());
            }
            catch(Exception error) {
                JOptionPane.showMessageDialog(this,"Erro " + error.getMessage());
            }
             
                try {
                IncEdi = new IncluirEditar();
                if(acao==1){
                   cod= IncEdi.Incluir(objAluno);
                   jcod.setText(String.valueOf(cod));
                   JOptionPane.showMessageDialog(this, "Salvo com sucesso");
                   salvar();
                                
                }catch(Exception error) {
                JOptionPane.showMessageDialog(this, "Operacao nao realizada" + error.getMessage());
                              
                }
                jbsalvar.setEnabled(false);
            }
    }//GEN-LAST:event_jbsalvarActionPerformed

    private void jbeditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbeditarActionPerformed

        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jbeditarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbcancelar;
    private javax.swing.JButton jbeditar;
    private javax.swing.JButton jbexcluir;
    private javax.swing.JButton jbnovo;
    private javax.swing.JButton jbpesquisar;
    private javax.swing.JButton jbsair;
    private javax.swing.JButton jbsalvar;
    private javax.swing.JTextField jcod;
    private javax.swing.JTextField jcpf;
    private com.toedter.calendar.JDateChooser jdata;
    private javax.swing.JTextArea jendereço;
    private javax.swing.JTextField jnome;
    private javax.swing.JTextField jrg;
    private javax.swing.JRadioButton jrnao;
    private javax.swing.JRadioButton jrsim;
    private javax.swing.JTextField jtelefone;
    // End of variables declaration//GEN-END:variables

    public void novo(){
    
    jnome.setEnabled(true);
    jendereço.setEnabled(true);
    jcpf.setEnabled(true);
    jrg.setEnabled(true);
    jtelefone.setEnabled(true);
    jcod.setEnabled(false);
    jbeditar.setEnabled(true);
    jbsalvar.setEnabled(true);
    jbcancelar.setEnabled(true);
    jrsim.setSelected(true);
    jcod.setText("");
    }

   public void salvar (){
    jnome.setEnabled(false);
    jendereço.setEnabled(false);
    jcpf.setEnabled(false);
    jrg.setEnabled(false);
    jtelefone.setEnabled(false);
    jcod.setEnabled(true);
    jbeditar.setEnabled(false);
    jbsalvar.setEnabled(false);
    jbcancelar.setEnabled(false);
    jrsim.setSelected(true);
    
    // limpando os campos.
    jnome.setText("");
    jendereço.setText("");
    jcpf.setText("");
    jrg.setText("");
    jtelefone.setText("");
  
   }
   public void preencher_objetos() {
       objAluno.setA_nome(jnome.getText().trim());
       objAluno.setA_rg(jrg.getText().trim());
       objAluno.setA_cpf(jcpf.getText().trim());
       objAluno.setA_end(jendereço.getText().trim());
       objAluno.setA_tel(jtelefone.getText().trim());
       objAluno.setA_ativo(ativo);
   }
}
